apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: k8s-netpol-synth-test-pipeline-run-
spec:
  pipelineRef:
    name: k8s-netpol-synth
  params:
  - name: repo-full-name
    value: np-guard/online-boutique-tekton
  - name: corporate-policies
    value:
    - https://github.com/np-guard/baseline-rules/blob/master/examples/restrict_access_to_payment.yaml
    - https://github.com/np-guard/baseline-rules/blob/master/examples/ciso_denied_ports.yaml
  - name: target-branch
    value: set_netpols_tekton
  workspaces:
  - name: ssh-creds
    # This secret can be created by running: kubectl create secret generic my-ssh-credentials --from-file=~/.ssh/known_hosts --from-file=~/.ssh/id_rsa
    secret:
      secretName: my-ssh-credentials
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: my-pvc
